# SITE CONFIGURATION
title: MUSSLES
author: John Letey
description: >
  Modeling and Uncertainty in Sea and Storm LEvelS
baseurl: ""
url: "https://mussles.github.io/"

# THEME SETTINGS
navigation:
  - {name: 'Home', link: '/'}
  - {name: 'Projects', link: '/projects'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modeling and Uncertainty in Sea and Storm LEvelS

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: anthony.e.wong@colorado.edu

github_username:  MUSSLES

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
